### ISSUE TITLE
Option: Add tab before JOIN setting

### ISSUE THREAD

**Issue by tziporaziegler** [TaoK/PoorMansTSqlFormatter#154] opened 2017-02-16 20:18 UTC
Currently, JOIN statements are formatted as following:
```
FROM TableA a(NOLOCK)
INNER JOIN TableB b(NOLOCK) ON a.Value1 = b.Value2
LEFT JOIN Table c(NOLOCK) ON b.Value3 = c.Value4
```

The way I usually format my code is:
```
FROM TableA a (NOLOCK)
    INNER JOIN TableB b (NOLOCK) ON a.Value1 = b.Value2
    LEFT JOIN Table c (NOLOCK) ON b.Value3 = c.Value4
```
I did not see any setting to change this formatting style.

Can this be added as a new setting?

![2017-02-16_1507](https://cloud.githubusercontent.com/assets/10053938/23038845/7c8c363a-f459-11e6-9d11-6456a3123ed1.png)

(I also am used to a space before (NOLOCK), but that's something that is easier to ignore.)

**Comment by TaoK** [comment] 2017-11-05 16:10
This is a duplicate of #59. It's not urgent in my books (anyone is welcome to implement of course, but this is not causing compatibility or deep usability issues), but there does seem to be a significant amount of interest!

**Closed by TaoK** 2017-11-05 16:10 UTC
