### ISSUE TITLE
MySQL support?

### ISSUE THREAD

**Issue by bestpika** [TaoK/PoorMansTSqlFormatter#147] opened 2016-08-23 02:12 UTC
Did this application support MySQL's query?
Like IF ... THEN ... ELSE ... END IF;

Thanks.

**Comment by TaoK** [comment] 2017-11-05 16:04
Closed as duplicate of #152.

(yes, that other one was added later, but has more / better detail)

**Closed by TaoK** 2017-11-05 16:04 UTC
