### ISSUE TITLE
Bug: Invlaid 

### ISSUE THREAD

**Issue by dbpromskelton** [TaoK/PoorMansTSqlFormatter#175] opened 2017-10-23 18:39 UTC
When expand comma lists is selected, and SELECT * query is passed, it errors with "Invalid Argument"

**Comment by TaoK** [comment] 2017-10-23 20:38
Again, example / context please. See #176

**Comment by dbpromskelton** [comment] 2017-10-23 20:44
Using SSMS 2017 and the vsix extension (newest), I get an invalid parameter error (though it runs anyway) when running this SQL through it, with the option "Expand Comma Lists" enabled. If I disable the option, or change the * to a comma sorted list of colums, it runs without error.

SELECT * FROM [mfg].[ProdStages] 

My coworker verified same behavior on his

On Oct 23, 2017, at 03:38 PM, Tao Klerks <notifications@github.com> wrote:

Again, example / context please. See #176

**Comment by TaoK** [comment] 2017-10-26 11:53
This is almost certainly a duplicate of Issue #168 - it should only be happening on very small queries (?), it seems to be something that everyone is noticing because they're testing with toy examples, rather than actually using the formatter normally.

**Comment by TaoK** [comment] 2017-10-26 15:01
Duplicate of #168

**Closed by TaoK** 2017-10-26 15:01 UTC
Labels: stalled
