### ISSUE TITLE
Bug: Group By

### ISSUE THREAD

**Issue by dbpromskelton** [TaoK/PoorMansTSqlFormatter#176] opened 2017-10-23 18:40 UTC
When Expand Comma lists is deselected and GROUP BY is passed via query, fails with error "Invalid Argument"

**Comment by TaoK** [comment] 2017-10-23 20:37
Not sure what you mean... What app are you using, what SQL are you formatting, can you provide some example code please?

**Comment by dbpromskelton** [comment] 2017-10-23 20:42
Using SSMS 2017 with Poor man vsix extension (newest), if I run this SQL (below) through it, I get an error "Invalid Parameter", but it still runs. THis is with the option "Expand Comma Lists is unchecked". If I remove the GROUP BY it runs with no error.

On Oct 23, 2017, at 03:37 PM, Tao Klerks <notifications@github.com> wrote:

Not sure what you mean... What app are you using, what SQL are you formatting, can you provide some example code please?

**Comment by TaoK** [comment] 2017-10-26 11:53
This is almost certainly a duplicate of Issue #168 - it should only be happening on very small queries (?), it seems to be something that everyone is noticing because they're testing with toy examples, rather than actually using the formatter normally.

**Comment by dbpromskelton** [comment] 2017-10-26 12:06
Mine were tested with regular real world examples

**Comment by TaoK** [comment] 2017-10-26 14:59
Another update on issue #168: It happens when the last line of the sql has text (is not an empty line), *and* the cursor is on that last line. Not as "toy scenario" as I had assumed.

**Comment by dbpromskelton** [comment] 2017-10-26 15:01
We decided on another solution due to the issues. Thanks

**Comment by TaoK** [comment] 2017-10-26 15:09
Alright, feel free to come back for some more issues another time! ;)

**Comment by TaoK** [comment] 2017-10-26 15:09
Duplicate of #168

**Closed by TaoK** 2017-10-26 15:09 UTC
Labels: stalled
