### ISSUE TITLE
SSMS 18.2 extension 1.6.16 - Disabled menu

### ISSUE THREAD

**Issue by Progress1** [TaoK/PoorMansTSqlFormatter#244] opened 2019-09-11 12:21 UTC
I have disabled actions menu (see picture). It looks that SSMS disable it, but i don't know why. Any experience with this?

![image](https://user-images.githubusercontent.com/10151485/64696610-1f358300-d49f-11e9-8a04-57d94732df60.png)

**Comment by alig114** [comment] 2019-09-16 12:23
I'm having the same issue on one of my machines. Has anyone figured out why this is happening?

**Comment by Progress1** [comment] 2019-09-24 07:40
Same behavior after upgrading to SSMS 18.3

**Comment by LuisLlamas** [comment] 2019-09-27 17:41
I'm having the same issue with SSMS 18.2 extension 1.6.16

**Comment by joydeepkarmakar** [comment] 2019-09-28 07:14
i am having the same issue with SSMS 18.2 extension 1.6.16

**Comment by srinivaspillalamarri** [comment] 2019-10-01 07:02
I'm also facing the same issue I'm using SSMS 18.1 extension 1.6.16

**Comment by AZITWB** [comment] 2019-10-01 13:21
Same on 18.3 extension 1.6.16

**Comment by Racoonator** [comment] 2019-10-04 12:43
Hi all,
Same issue with Windows 10 Enterprise 1903, SSMS 18.3.
Regards

**Comment by AZITWB** [comment] 2019-10-05 07:57
Installed SSMS 17.6 and now  in 18.3 plugin is working :)

**Comment by Racoonator** [comment] 2019-10-07 09:30
Hi,

I installed SSMS 17.9.1 and just after I uninstalled it and now Poor Man Sql works in SSMS 18.3
During the install of 17.9 version, I notice some package relating to VS 2015 was installed.

These packages are still here after the removal of SSMS 17.9
- Microsoft Visual Studio 2015 Shell (Isolated)
- Microsoft Visual Studio Tools for Applications 2015 
- Microsoft Visual Studio Tools for Applications 2015 Language Support

I don't know if it's really the reason why now Poor Man works in 18.3, but I can just say the famous "on my computer, it works!"

**Comment by RichardDavies** [comment] 2019-10-09 20:41
I believe this is a duplicate of (or at least related to) #234

**Comment by GelterMacias** [comment] 2019-10-09 22:27
> Hi,
> 
> I installed SSMS 17.9.1 and just after I uninstalled it and now Poor Man Sql works in SSMS 18.3
> During the install of 17.9 version, I notice some package relating to VS 2015 was installed.
> 
> These packages are still here after the removal of SSMS 17.9
> 
> * Microsoft Visual Studio 2015 Shell (Isolated)
> * Microsoft Visual Studio Tools for Applications 2015
> * Microsoft Visual Studio Tools for Applications 2015 Language Support
> 
> I don't know if it's really the reason why now Poor Man works in 18.3, but I can just say the famous "on my computer, it works!"

I followed the suggest from Racoonator and worked for me too.
Thank you.

**Comment by agilotel** [comment] 2019-11-02 16:33
Recommendation from Racoonator worked for me - thanks!

**Comment by srinivaspillalamarri** [comment] 2019-11-03 10:10
Microsoft Visual Studio Isolated Shell  is the best solution
Look into following video I got resolved this
https://youtu.be/jcAsmND1C2I

**Comment by Progress1** [comment] 2019-11-04 09:45
330Mb installation (just setup) to solve disabled menu :D 
Is it necessary or it can be solved with some other way? Maybe add-on can be created/compiled without this dependency. Or is MS VS Isolated Shell mandatory to create SSMS add-ons?

**Comment by srinivaspillalamarri** [comment] 2019-11-04 11:23
> 330Mb installation (just setup) to solve disabled menu :D
> Is it necessary or it can be solved with some other way? Maybe add-on can be created/compiled without this dependency. Or is MS VS Isolated Shell mandatory to create SSMS add-ons?

I tried with piece by piece installation but I'm not able reach the solution.

But when I checked "**ActivityLog.xml**" from "**AppData\Roaming\Microsoft\AppEnv\15.0**" I got one line **CreateInstance Failed for package [FormatterPackage]Source: Description: Could not load file assembly Microsoft.VisualStudio.Shell.12.0**. By looking at this line I became to know that we need this.
That is why tried with VS Shell and I got resolved my issue

**Comment by nhasibuan** [comment] 2019-11-20 03:28
Microsoft SQL Server Management Studio						12.0.2000.8
Microsoft Analysis Services Client Tools						12.0.2000.8
Microsoft Data Access Components (MDAC)						10.0.18362.1
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.18362.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.18362

PoorMansTSqlFormatterSSMSPackage.Setup.1.6.16 not working

**Comment by mika76** [comment] 2019-12-03 08:02
Doesn't work in 18.4 either - I really wish MS would stop changing the bloody dependencies so much...

**Comment by fhaider2000** [comment] 2019-12-03 14:29
same issue using 18.4

**Comment by rishipkothari** [comment] 2019-12-13 00:29
> Microsoft Visual Studio Isolated Shell is the best solution
> Look into following video I got resolved this
> https://youtu.be/jcAsmND1C2I

Same issue on a fresh PC Win 10 1803 SSMS 18.4, resolved with installing Visual Studio 2015 Isolated Shell per above.

**Comment by m1hammer** [comment] 2020-01-19 21:21
Had this problem on Win10 1903, SSMS 18.4, and PoorSQL 1.6.16 
Installing VS 2015 isolated shell fixed it as well, but that seems like a band-aid solution. 
It's such a great tool...I wish MS would stop pulling the rug out...

**Comment by wkraft01** [comment] 2020-02-04 21:15
I had this issue, installing Isolated shell solved it. I suggest adding a note for this on the download page or making a prerequisite check for it  in the  PoorSql installer.

**Comment by BraINstinct0** [comment] 2020-02-13 04:50
Same issue confirmed on SSMS 18.4/Windows 10 Home 1909/Visual Studio 2019/VS Code/PoorSQL 1.6.16 for SSMS. (Shows 'FormatterPackage' load error as in #234 on first startup.)
Installing VS15 Isolated Shell did indeed solve the problem.

**Comment by kjo1** [comment] 2020-10-25 22:31
> Microsoft Visual Studio Isolated Shell is the best solution
> Look into following video I got resolved this
> https://youtu.be/jcAsmND1C2I

Thank you, the problem solved.

https://aka.ms/VS2015/IsoShell/en-US

![image](https://user-images.githubusercontent.com/44075333/97120805-43c6db80-16f0-11eb-8b78-9a6fd20a1060.png)

**Comment by EltonInAtlanta** [comment] 2020-11-17 16:35
I encountered this with SSMS 18.6.  This is the solution I found.

Edit ssms.exe.config
C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE

In `<assemblyBinding>` Add

`<dependentAssembly> <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/> <bindingRedirect oldVersion="2.0.0.0-15.0.0.0" newVersion="15.0.0.0"/> </dependentAssembly>
`

**Comment by Progress1** [comment] 2020-11-18 07:00
> I encountered this with SSMS 18.6. This is the solution I found.
> Edit ssms.exe.config ...

Nice solution!

**Comment by r14958** [comment] 2020-12-28 21:31
Work for me, too.  Thanks!

**Comment by ricky-small** [comment] 2021-01-26 23:09
> I encountered this with SSMS 18.6. This is the solution I found.
> 
> Edit ssms.exe.config

This was the solution for me as well. Thanks!

**Comment by GraemeJones104** [comment] 2021-02-17 07:22
> 
> 
> I encountered this with SSMS 18.6. This is the solution I found.
> 
> Edit ssms.exe.config
> C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE
> 
> In `<assemblyBinding>` Add
> 
> `<dependentAssembly> <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/> <bindingRedirect oldVersion="2.0.0.0-15.0.0.0" newVersion="15.0.0.0"/> </dependentAssembly> `

Worked for me too! Noting, when I tried installing isolated shell that failed. This is a much simpler solution. Nice work!

**Comment by surendra37** [comment] 2021-05-19 15:05
This worked for me as well for v18.9.1

**Comment by alexbousquet** [comment] 2021-06-07 15:05
Was attempting the Isolated Shell solution per the top Google result, but that installer wanted me to uninstall the Visual C++ 2015 Redistributable (x86 and x64) to continue.

I went to Apps/Features and clicked "Modify" on the x86 version to see my options before potentially causing more problems. I clicked the "Repair" button in the wizard and it quickly finished. Opened up SSMS and options are actually available now!

I was honestly shocked... I think that's the first time a "Repair" button has actually fixed something for me. 🤣

**Comment by DjJazzyJeffTN** [comment] 2021-08-12 17:26
> Microsoft Visual Studio Isolated Shell is the best solution
> Look into following video I got resolved this
> https://youtu.be/jcAsmND1C2I

This guy (@srinivaspillalamarri) nailed it! Good video and thanks for the post.

**Comment by heerten** [comment] 2021-11-11 11:20
> I encountered this with SSMS 18.6. This is the solution I found.
> 
> Edit ssms.exe.config C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE
> 
> In `<assemblyBinding>` Add
> 
> `<dependentAssembly> <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/> <bindingRedirect oldVersion="2.0.0.0-15.0.0.0" newVersion="15.0.0.0"/> </dependentAssembly> `

Quick and easy fix. Remeber to edit the file in administrator mode, otherwise you can't save it ;-)
This solved the problem for me, I have SSMS 18.10 installed and now TSQL formatter works like a charm as is already did in Notepad++.
Thanks a lot!

**Comment by berkcinazz** [comment] 2021-11-12 12:30
> Microsoft Visual Studio Isolated Shell is the best solution Look into following video I got resolved this https://youtu.be/jcAsmND1C2I

This also worked for me. Thx a lot.

**Comment by Lalo11r** [comment] 2022-01-12 02:15
> I encountered this with SSMS 18.6. This is the solution I found.
> 
> Edit ssms.exe.config C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE
> 
> In `<assemblyBinding>` Add
> 
> `<dependentAssembly> <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/> <bindingRedirect oldVersion="2.0.0.0-15.0.0.0" newVersion="15.0.0.0"/> </dependentAssembly> `

This worked for me as well, thxs!!

**Comment by khansadi** [comment] 2022-03-11 18:55
> I encountered this with SSMS 18.6. This is the solution I found.
> 
> Edit ssms.exe.config C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE
> 
> In `<assemblyBinding>` Add
> 
> `<dependentAssembly> <assemblyIdentity name="Microsoft.VisualStudio.Shell.12.0" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/> <bindingRedirect oldVersion="2.0.0.0-15.0.0.0" newVersion="15.0.0.0"/> </dependentAssembly> `

Awesome find!!

**Closed as completed** 2023-12-21 11:30 UTC
